// frontend/src/components/MatchHistoryList.jsx
import MatchCard from './MatchCard';

export default function MatchHistoryList({ games }) {
  if (!games || games.length === 0) {
    return (
      <div className="bg-white rounded-xl shadow-sm p-12 text-center text-gray-400 text-sm">
        해당 큐의 게임 기록이 없습니다
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2">
      {games.map((game) => (
        <MatchCard key={game.gameId} game={game} />
      ))}
    </div>
  );
}

// frontend/src/components/MatchHistoryList.vue
﻿<script setup>
import MatchCard from './MatchCard.vue'

defineProps({
  games: { type: Array, required: true },
})
</script>

<template>
  <div v-if="games.length === 0" class="bg-white rounded-xl shadow-sm p-12 text-center text-gray-400 text-sm">
    해당 모드의 게임 기록이 없습니다
  </div>
  <div v-else class="flex flex-col gap-2">
    <MatchCard v-for="game in games" :key="game.gameId" :game="game" />
  </div>
</template>
